[package]
edition = '2018'
name = "deploy-flake"
version = "0.0.1-dev"
authors = ["Andreas Fuchs <asf@boinkor.net>"]
license = "MIT"
repository = "https://github.com/antifuchs/deploy-flake"
readme = "README.md"
description = "Deploy a nix flake to a remote system"
documentation = "https://docs.rs/deploy-flake"

[[bin]]
name = "deploy-flake"
path = "src/main.rs"

[badges]
travis-ci = { repository = "antifuchs/deploy-flake", branch = "master" }
maintenance = { status = "passively-maintained" }

[package.metadata.template_ci.clippy]
allow_failure = false
version = "stable"

[dependencies]
clap = "3.0.0-beta.5"
anyhow = "1.0.40"
serde_json = "1.0.79"
serde = { version = "1.0.136", features = ["derive"] }
openssh = "0.8.1"
tokio = { version = "1.5.0", features = ["full"] }
async-trait = "0.1.53"
tracing = "0.1.32"
tracing-subscriber = "0.3.10"
